### ISSUE TITLE
centos7

### ISSUE THREAD

**Issue by novvoo** [luodaoyi/CloudFlarePartner#1]
**1.** 两个yml版本不一样报错
**2.** 镜像名字不能大写的
**3.** 拉取不到镜像
`ERROR: pull access denied for luodaoyi/cloudflarepartnner, repository does not exist or may require 'docker login'`

**Comment by novvoo** [comment]
你的镜像应该是 luodaoyi/cloudflarepartner

**Comment by luodaoyi** [comment]
docker-compose 配置文件已修复。

另外请使用ubuntu
